### PR TITLE
Allow 4.x language packes to be installed on J4.2 too

### PR DESCRIPTION
**Pull request by zero-24**
cc @brianteeman https://github.com/joomla/joomla-cms/issues/37018#issue-1134564743

cc @wilsonge @HLeithner

### CODE REVIEW

**Review by wilsonge — APPROVED** [review]

**Review by HLeithner — APPROVED** [review]

**Comment by brianteeman** [comment]
bump

**Comment by zero-24** [comment]
@HLeithner @wilsonge can you please merge here and push the changes to the server? Thanks

**Comment by brianteeman** [comment]
bump again

**Comment by wilsonge** [comment]
Merging. Will install this early next week as currently on holiday with only mobile. Please ping again if not sorted by next Thursday

**Comment by wilsonge** [comment]
Found someone to borrow a laptop from. Uploaded.

**Comment by zero-24** [comment]
Thanks @wilsonge 👍

**Pull request merged**
