### PR TITLE
Allow 4.x language packages to be installed on J4.4 too

### PR DESCRIPTION
**Pull request by heelc29**

### CODE REVIEW

**Review by tecpromotion — APPROVED** [review]
Thanks @heelc29

**Comment by heelc29** [comment]
@tecpromotion Does someone have to upload the changes?
[details4/de-DE_details.xml](https://downloads.joomla.org/index.php?option=com_languagepack&view=export&format=xml&cms_version=40&language_code=de-DE)
`<targetplatform name="joomla" version="4.[0123]"/>`

**Comment by tecpromotion** [comment]
> @tecpromotion Does someone have to upload the changes? [details4/de-DE_details.xml](https://downloads.joomla.org/index.php?option=com_languagepack&view=export&format=xml&cms_version=40&language_code=de-DE) `<targetplatform name="joomla" version="4.[0123]"/>`

I'll discuss it with @HLeithner on Friday.

**Comment by tecpromotion** [comment]
@Llewellynvdm can you please take a look here and then deploy them.
Thank you.

**Comment by Llewellynvdm** [comment]
Okay I have updated the language-pack extension on the download website it will take a day or so to be picked-up by the update server, and correctly reflect in the static XML files.

This is the dynamic endpoint: https://downloads.joomla.org/index.php?option=com_languagepack&view=export&format=xml&cms_version=40&language_code=de-DE
But the static endpoint that will auto-update it here:  https://update.joomla.org/language/details4/de-DE_details.xml

These static files is what is linked to the CMS, and so they take a day or so to auto-update.

**Pull request merged**
