### PR TITLE
Make sure there are no spaces in the language zip name

### PR DESCRIPTION
**Pull request by zero-24**
@wilsonge that should be a sensible additional validation. But will debug once I got access to.

### CODE REVIEW

**Comment by wilsonge** [comment]
Had to change typehint to a string because we strict check it further down. Will try and stick it on the server later.

**Review by wilsonge — APPROVED** [review]

**Comment by conconnl** [comment]
I just found out that multiple uploads of the German language were broken.
Probably because of using a space.
I fixed all the releases.

Someone also used Version while the upload field states 4.0.1 as example.
Maybe not completely clear.

**Comment by zero-24** [comment]
Hmm we might setup an field validation making sure that only a valid version strings can be entered there.

> I fixed all the releases.

Great thanks.

**Comment by Llewellynvdm** [comment]
Yes adding field validation would be ideal :+1:

**Comment by zero-24** [comment]
How would such a validation look like?l in your opinion?

Check for integers, dots and -alpha, -beta, -rc?
Check against the published tags on GitHub?

**Comment by Llewellynvdm** [comment]
Here is an idea:
```php
<?php
/**
 * @package     Joomla.Site
 * @subpackage  com_languagepack
 *
 * @copyright   Copyright (C) 2020 - 2021 Open Source Matters, Inc. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

// No direct access to this file
defined('JPATH_PLATFORM') or die;

use Joomla\CMS\Form\Form;
use Joomla\CMS\Form\FormRule;
use Joomla\Registry\Registry;

/**
 * Form Rule (Validversion) class for the Joomla Platform.
 */
class JFormRuleValidversion extends FormRule
{
	/**
	 * Method to test that an integer value was added.
	 *
	 * @param   \SimpleXMLElement  $element  The SimpleXMLElement object representing the `<field>` tag for the form field object.
	 * @param   mixed              $value    The form field value to validate.
	 * @param   string             $group    The field name group control value. This acts as an array container for the field.
	 *                                       For example if the field has name="foo" and the group value is set to "bar" then the
	 *                                       full field name would end up being "bar[foo]".
	 * @param   Registry           $input    An optional Registry object with the entire data set to validate against the entire form.
	 * @param   Form               $form     The form object for which the field is being tested.
	 *
	 * @return  boolean  True if the value is valid version, false otherwise.
	 *
	 */
	public function test(\SimpleXMLElement $element, $value, $group = null, Registry $input = null, Form $form = null)
	{
		// Check if the field is required.
		$required = ((string) $element['required'] == 'true' || (string) $element['required'] == 'required');

		// If the value is empty and the field is not required return True.
		if (($value === '' || $value === null) && ! $required)
		{
			return true;
		}

		// check that the string has no whitespace
		// not sure about this as we could remove whitespace instead
		// but this will catch it here
		if (preg_match('/\s/', $value))
		{
			return false;
		}

		// check the formats allowed:
		// 22.22.22-rc
		// 1919.121.1212-beta
		// 3.8.5
		// 3.8.10-beta
		// 3.8-beta
		// 4.0
		if(preg_match('/^((\d+)\.(\d+)(\.(\d+))?(-rc)?(-beta)?(-alpha)?)$/', $value))
		{
			return true;
		}

		return false;
	}
}
```
Just a quick option... if we want to limit it more towards only set of tags then we need to get that set in the mix as well.

**Comment by zero-24** [comment]
That looks good so on a quick look. I'm no regex profi but after -alpha, -beta, -rc we should allow numbers again :-)

**Comment by zero-24** [comment]
And we should force the full vrrsion string. So "4" or "4.0" would be invalid. Only 3.9.28 or 4.0.0 would be valid

**Comment by conconnl** [comment]
It should be:
{numbers}. {numbers}. {numbers}[-alpha,-beta, or -rc]{numbers}

**Comment by zero-24** [comment]
Agree I would say rc22 is valid too.

**Comment by wilsonge** [comment]
Closing for #55

**Pull request closed without merging**
