### PR TITLE
Allow 4.x language packes to be installed on J4.3 too

### PR DESCRIPTION
**Pull request by zero-24**
cc @HLeithner

### CODE REVIEW

**Comment by HLeithner** [comment]
thanks

**Comment by brianteeman** [comment]
Has this been deployed?

All the language files are only marked upto 4.2 so I cant test with 4.3
https://update.joomla.org/language/details4/fr-FR_details.xml

**Comment by tecpromotion** [comment]
@brianteeman, @zero-24 and @HLeithner fyi
@Llewellynvdm will take a look at this and, if necessary, carry out the deploy.

**Comment by brianteeman** [comment]
thanks - if it turns out that it has been deployed then there is another problem

**Comment by Llewellynvdm** [comment]
There is the auto-generated XML and the static XML of these files. The auto-generated xml is managed by this change. Auto as in it looks at what is in the database and builds the XML needed to guide the update. But we move these auto generated files to another server and it is from that server that all of those using Joomla consumes the xml. This removes a huge load from the server generating it over and over.

So since this update to the automated build part of the XML should work if deployed we need only check that the second part of the architecture then builds the static files. So there is only these two places we need to look at.

This extension (automated xml builder) runs on downloads.joomla.org and the static files live on update.joomla.org

The script the pulls the files from the download.joomla.ord server and places un the update.joomla.org serve can be found here: https://github.com/joomla/update.joomla.org/tree/master/translation-sh

That script really needs very little maintenance as it is config driven... but I will check up on it to make sure all still run as expected. Since this is the same script that has been updating all the xml all this time since we moved to 4.0 => 4.2 and now 4.3 and we never had to make any changes to it. As the versioning is manage on the auto-build side of the XML pipeline.

Hope this makes sense. Let me know if anything remains unclear.

**Comment by brianteeman** [comment]
no idea what you are saying - and I dont need to know - all i know is that the language files are all limited to 4.[0,1,2] so they can NOT be installed on joomla 4.3 which makes real tests of 4.3 impossible.

when this happened previously I was told this script was responsible.

we just need people to be able to test joomla and right now they can not

**Comment by Llewellynvdm** [comment]
Here is the list of all languages https://downloads.joomla.org/index.php?option=com_languagepack&view=export&format=xml&cms_version=40 (auto generated from the data we have)

Here is then the French output of the auto generated xml https://downloads.joomla.org/index.php?option=com_languagepack&view=export&format=xml&cms_version=40&language_code=fr-FR

Soon as the update script that moves the static files into place run on the update server this file will be updated: https://update.joomla.org/language/details4/fr-FR_details.xml

Since I update the extension and the correct `4.[0,1,2,3]` value is not in the dynamic text, it should reflect in the static text any time soon.

**Comment by tecpromotion** [comment]
XML file looks fine now. 

@brianteeman can you check please.

**Comment by brianteeman** [comment]
confirmed working - thanks

**Pull request merged**
